# Generated by Django 5.0.6 on 2024-06-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
