# Generated by Django 5.0.6 on 2024-06-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_movie_title_alter_series_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
